language: python
env:
   - DJANGO='>=1.8,<1.9'
   - DJANGO='>=1.9,<1.10'
   - DJANGO='>=1.10,<1.11'
   - DJANGO='>=1.11,<1.12'
   - DJANGO='>=2.0,<2.1'
python:
   - "2.7.13"
   - "3.6"
matrix:
    exclude:
    - env: DJANGO='>=2.0,<2.1'
      python: "2.7.13"
install:
   - pip install --no-deps -e .
   - pip install -r requirements/requirements_test.txt
   - pip install "statsd==3.2.1"
   - pip install "Django${DJANGO}"
before_script:
    flake8 django_statsd/
script:
    pytest -v --capture=sys --cov=django_statsd/ django_statsd/ --cov-report term-missing:skip-covered
after_success:
    coveralls
